name: action-test
on:
  workflow_dispatch:
    inputs:
      distinct_id:
        required: true
      branch_id:
        required: false
      cake: # Test for input passthrough.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: echo branch ID ${{ github.event.inputs.branch_id }}
        run: echo ${{ github.event.inputs.branch_id }}
      - name: echo input passthrough
        run: echo ${{ github.event.inputs.cake }}
